### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by ddubs13** [feliskio/discord-live-translator#14]
I have server permissions. I invited it to the server. Me and a friend who speaks spanish joined a voice call. I invited the bot.

Typed "!translation join" and then "!translation en es". It joined the call, did a sound effect, but didn't work after that. Does it only translate text?

**Comment by feliskio** [comment]
Can you give me the name of the Discord server/guild at that time that you were on. This would allow me to take a look at the logs that the bot has generated.
If you feel uncomfortable publicly naming the server here feel free to shoot me a message through the [contact form on my website](https://felisk.io/#contact).

**Comment by feliskio** [comment]
Still awaiting response. @ddubs13

**Comment by feliskio** [comment]
No response - closed.
