### ISSUE TITLE
Bot is Offline and dont answers Commands

### ISSUE THREAD

**Issue by Tagor322** [feliskio/discord-live-translator#18]
Hey, 

i have a problem with my Server. I created a new Server for Testing and Invited the Bot from the Website. The Bot is visible under users of the Server, but he is Offline. When i type commands like !translation join or other command he dont repley to the commands. I tried to add the nvo.io Text translate Bot and that is working and that answers in Text Channel.

Can someone help me pls? 

Thanks!

**Comment by feliskio** [comment]
Thank you for bringing this to my attention!
I will investigate the issue and comment once it is fixed.

**Comment by feliskio** [comment]
The root problem is fixed and the bot back online.
