### ISSUE TITLE
"The command !translation is no longer supported" 

### ISSUE THREAD

**Issue by JohnGilbert1** [feliskio/discord-live-translator#19]
Hello,

I just added your bot to my server for testing, but it keeps showing me this error. Is there new command or what happen here?

![Screenshot_20220207-150716_Bluecord](https://user-images.githubusercontent.com/14311768/152803348-58fa9d5f-c0ac-4f9a-af4d-776d37ba52e9.jpg)

**Comment by feliskio** [comment]
This behavior is expected as the bot was recently migrated to use Discord's native slash commands. The old `!translation` command now throws this error message to ease the transition for existing users.
If you start a message in any channel starting with a forward slash (/) you will see all the commands provided by the bot.
