### ISSUE TITLE
I know this issue is very vague but it appears to have stopped working?

### ISSUE THREAD

**Issue by reisu1337** [feliskio/discord-live-translator#24]
Invited it into a server with some spanish friends and ran /join. The bot joined (and made the join noise), but after running the start command (in this case /start spanish english) nothing happened. Tried enunciating and different languages but no output. Can provide more details if needed :)

**Comment by feliskio** [comment]
Hi, thanks for reporting this. The bot should be available again.
The takeaway from this should be: Don't always auto-update to the latest semi-stable release. One of the bot's dependencies (LibreTranslate) had a faulty update, which made it constantly crash and therefore not available for the bot to use. This in turn meant that the bot wasn't able to perform any translations.

**Comment by reisu1337** [comment]
Seems to be working now, thanks!
